version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: rabbitmq
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    ports:
      - 5672:5672
      - 15672:15672
  
  scraper:
    image: themulti0/scraper:latest
    container_name: scraper
    build:
      context: src
      dockerfile: Scraper.MassTransit/Dockerfile
    volumes: 
      - './Scraper.MassTransit/appsettings.json:/app/appsettings.json'

  postslistener:
    image: themulti0/postslistener:latest
    container_name: postslistener
    build:
      context: src
      dockerfile: PostsListener/Dockerfile
    volumes:
      - './PostsListener/appsettings.json:/app/appsettings.json'