version: '3.4'

services:
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: 'rabbitmq'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    ports:
      - 5672:5672
      - 15672:15672