name: Build and publish PostsListener.Client

on:
  workflow_dispatch:
  push:
    paths:
      - "src/PostsListener.Client/**"
      - "test/PostsListener.Client.Tests/**"
  pull_request:
    paths:
      - "src/PostsListener.Client/**"
      - "test/PostsListener.Client.Tests/**"

env:
  DOTNET_VERSION: 5.0.x

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.6-management-alpine
        ports:
          - 5672:5672
      
      scraper:
        image: themulti0/scraper:latest
      
      postslistener:
        image: themulti0/postslistener:latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore src/PostsListener.Client
      
    - name: Build
      run: dotnet build --no-restore src/PostsListener.Client
      
    - name: Test
      run: dotnet test --no-build test/PostsListener.Client.Tests
      
  publish:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/PostsListener.Client/PostsListener.Client.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        TAG_COMMIT: false