name: Build and publish Scraper.RabbitMq.Client

on:
  workflow_dispatch:
  push:
    paths:
      - "src/Scraper.RabbitMq.Client/**"
  pull_request:
    paths:
      - "src/Scraper.RabbitMq.Client/**"

env:
  DOTNET_VERSION: 5.0.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore src/Scraper.RabbitMq.Client
      
    - name: Build
      run: dotnet build --no-restore src/Scraper.RabbitMq.Client

  publish:

    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Scraper.RabbitMq.Client/Scraper.RabbitMq.Client.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        TAG_COMMIT: false