name: Build and publish Scraper.MassTransit.Client

on:
  workflow_dispatch:
  push:
    paths:
      - "src/Scraper.MassTransit.Client/**"
      - "test/Scraper.MassTransit.Client.Tests/**"
  pull_request:
    paths:
      - "src/Scraper.MassTransit.Client/**"
      - "test/Scraper.MassTransit.Client.Tests/**"

env:
  DOTNET_VERSION: 5.0.x

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.6-management-alpine
        ports:
          - 5672:5672

      scraper:
        image: themulti0/scraper:latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore src/Scraper.MassTransit.Client
      
    - name: Build
      run: dotnet build --no-restore src/Scraper.MassTransit.Client
      
    - name: Test
      run: dotnet test --no-build test/Scraper.MassTransit.Client.Tests

  publish:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Scraper.MassTransit.Client/Scraper.MassTransit.Client.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
        TAG_COMMIT: false