name: Build and publish Scraper.MassTransit

on:
  workflow_dispatch:  
  push:
    paths:
      - "src/Scraper.MassTransit/**"
  pull_request:
    paths:
      - "src/Scraper.MassTransit/**"
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore src/Scraper.MassTransit

      - name: Build
        run: dotnet build --no-restore src/Scraper.MassTransit
  
  publish:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.1
        with:
          context: src
          file: src/Scraper.MassTransit/Dockerfile
          push: true
          tags: themulti0/Scraper.MassTransit:latest
